- name: Add EC2 host dynamically
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Dynamisch EC2 Host hinzufügen
      ansible.builtin.add_host:
        name: ec2_target
        ansible_host: "{{ ec2_ip }}"
        ansible_user: ubuntu
        groups: ec2_dynamic_group

- name: Setup RIA Demo Cluster
  hosts: ec2_dynamic_group
  become: true

  roles:
    - ria-demo
