---
- name: Scale Microservice on the chosen backend
  hosts: role_backend
  become: true
  gather_facts: false
  vars:
    microservice_name: ""
    replica_count: "3"
    app_namespace: "super-automation-demo"
  tasks:
    - name: Scale {{ microservice_name }}
      ansible.builtin.shell: |
        kubectl scale --replicas={{ replica_count }} deployment {{ microservice_name }} -n {{ app_namespace }}
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
