- name: Add host dynamically
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Dynamisch Host hinzufügen
      ansible.builtin.add_host:
        name: ec2_target
        ansible_host: "{{ ec2_ip }}"
        ansible_user: "{{ remote_user }}"
        groups: ec2_dynamic_group

- name: Setup Super Demo
  hosts: ec2_dynamic_group
  become: true

  roles:
    - ria-demo
