#SPDX-License-Identifier: MIT-0
---
# tasks file for ria-demo

- name: Install dependencies
  ansible.builtin.include_tasks:
    file: setup_deps.yaml
    apply:
      tags:
        - deps
  tags:
    - deps

- name: Include K3S Setup
  ansible.builtin.include_tasks:
    file: setup_k3s.yaml
    apply:
      tags:
        - k3s
  tags:
    - k3s

- name: Include Instana Agent Setup
  ansible.builtin.include_tasks:
    file: setup_instana_agent.yaml
    apply:
      tags:
        - instana
  tags:
    - instana

- name: Include Instana Appview Setup
  when: service_type == 'frontend'
  ansible.builtin.include_tasks:
    file: setup_instana_appview.yaml
    apply:
      tags:
        - instana_appview
  tags:
    - instana_appview

- name: Include Deployment of Flight Monitor App
  when: app_name == 'flightmonitor'
  ansible.builtin.include_tasks:
    file: setup_deploy_example_app.yaml
    apply:
      tags:
        - flightmonitor
  tags:
    - flightmonitor

- name: Include Deployment of Quote of the Day App
  when: app_name == 'qotd'
  ansible.builtin.include_tasks:
    file: setup_deploy_qotd.yaml
    apply:
      tags:
        - qotd
  tags:
    - qotd

- name: Include Deployment of RobotShop App
  when: app_name == 'robotshop'
  ansible.builtin.include_tasks:
    file: setup_deploy_robot_shop.yaml
    apply:
      tags:
        - robotshop
  tags:
    - robotshop

- name: Setup Turbonomic Connection
  ansible.builtin.include_tasks:
    file: setup_kubeturbo.yaml

- name: Include HCM Agent Setup
  ansible.builtin.include_tasks:
    file: setup_hcm_agent.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm

- name: Include HCM Backend Setup
  ansible.builtin.include_tasks:
    file: setup_hcm_backend.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm
