#SPDX-License-Identifier: MIT-0
---
# tasks file for ria-demo
- name: Install dependencies
  ansible.builtin.include_tasks:
    file: setup_deps.yaml
    apply:
      tags:
        - deps
  tags:
    - deps

- name: Include K3S Setup
  ansible.builtin.include_tasks:
    file: setup_k3s.yaml
    apply:
      tags:
        - k3s
  tags:
    - k3s

################# Feature Flags for Components ####x
- name: Include SNMP Setup for SevOne
  when: feature_sevone | bool
  ansible.builtin.include_tasks:
    file: setup_snmp.yaml
    apply:
      tags:
        - snmp
        - sevone
  tags:
    - snmp
    - sevone

- name: Include Instana Agent Setup
  when: feature_instana | bool
  ansible.builtin.include_tasks:
    file: setup_instana_agent.yaml
    apply:
      tags:
        - instana
  tags:
    - instana

- name: Include HCM Agent Setup
  when: (feature_hcm | bool) and (service_type != "full")
  ansible.builtin.include_tasks:
    file: setup_hcm_agent.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm

- name: Include HCM Backend Setup
  when: (feature_hcm | bool) and (service_type != "full")
  ansible.builtin.include_tasks:
    file: setup_hcm_backend.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm

- name: Include KubeCost Setup
  when: feature_kubecost | bool
  ansible.builtin.include_tasks:
    file: setup_kubecost.yaml
    apply:
      tags:
        - kubecost
  tags:
    - kubecost
###################################################

################# App Deployment ##################
- name: Include Instana Appview Setup
  when: service_type == 'frontend' and app_name
  ansible.builtin.include_tasks:
    file: setup_instana_appview.yaml
    apply:
      tags:
        - instana_appview
  tags:
    - instana_appview

- name: Include Deployment of Flight Monitor App
  when: app_name == 'flightmonitor'
  ansible.builtin.include_tasks:
    file: setup_deploy_flightmonitor.yaml
    apply:
      tags:
        - flightmonitor
  tags:
    - flightmonitor

- name: Include Deployment of Quote of the Day App
  when: app_name == 'qotd'
  ansible.builtin.include_tasks:
    file: setup_deploy_qotd.yaml
    apply:
      tags:
        - qotd
  tags:
    - qotd

- name: Include Deployment of RobotShop App
  when: app_name == 'robotshop'
  ansible.builtin.include_tasks:
    file: setup_deploy_robot_shop.yaml
    apply:
      tags:
        - robotshop
  tags:
    - robotshop

- name: Setup Turbonomic Connection
  ansible.builtin.include_tasks:
    file: setup_kubeturbo.yaml
    apply:
      tags:
        - turbo
  tags:
    - turbo
        
- name: Include HCM Agent Setup
  ansible.builtin.include_tasks:
    file: setup_hcm_agent.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm

- name: Include HCM Backend Setup
  ansible.builtin.include_tasks:
    file: setup_hcm_backend.yaml
    apply:
      tags:
        - hcm
  tags:
    - hcm
