- name: Get public IP
  ansible.builtin.shell: curl -s http://checkip.amazonaws.com
  register: ec2_public_ip

- name: Install k3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --disable servicelb" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Start k3s service
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Ensure k3s config is readable
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: "0755"

- name: Install kubectl binary link
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Wait for Kubernetes API to become available
  become: false
  retries: 20
  delay: 5
  register: result
  until: result.rc == 0
  ansible.builtin.shell: kubectl get nodes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- name: Install MetalLB via Helm
  ansible.builtin.shell: helm install   metallb oci://registry.suse.com/edge/charts/metallb   --namespace metallb-system   --create-namespace
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- name: Copy and apply MetalLB Resources (IP Pool)
  ansible.builtin.template:
    src: files/metallb-ip.yml
    dest: /tmp/ips.yml
    mode: '0644'
    
- name: Copy and apply MetalLB Resources (Advert)
  ansible.builtin.copy:
    src: files/metallb-advert.yml
    dest: /tmp/advert.yml
    mode: '0644'
- name: apply MetalLB CRs
  ansible.builtin.shell: kubectl apply -f {{ item }}
  loop:
  - /tmp/advert.yml
  - /tmp/ips.yml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
- name: Add Traefik Helm repo
  ansible.builtin.shell: helm repo add traefik https://traefik.github.io/charts
  args:
    creates: /root/.cache/helm/repository/traefik-index.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Update Helm repos
  ansible.builtin.shell: helm repo update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Copy traefik.yaml to target
  ansible.builtin.copy:
    src: files/traefik.yaml
    dest: /tmp/traefik.yaml
    mode: '0644'

- name: Install Traefik via Helm with fixed NodePorts
  ansible.builtin.shell: |
    helm upgrade --install traefik traefik/traefik \
      --namespace kube-system \
      --create-namespace \
      -f /tmp/traefik.yaml \
      --wait
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
