# Deployment of the App Quote of the Day: https://gitlab.com/quote-of-the-day/quote-of-the-day/
- name: Add Helm-Repo for Qotd
  ansible.builtin.shell: |
    helm repo add {{ qotd_repo_name }} {{ qotd_repo_url }}

- name: Update Helm-Repos
  ansible.builtin.shell: |
    helm repo update

- name: Create needed namespaces
  ansible.builtin.shell: |
    kubectl create namespace {{ app_namespace }}
    kubectl create namespace {{ app_namespace }}-load
  register: create_namespaces_result
  failed_when: create_namespaces_result.rc != 0 and
               "AlreadyExists" not in create_namespaces_result.stderr

- name: Install Quote of the day with Helm
  ansible.builtin.shell: |
    helm install qotd2 {{ qotd_repo_name }} \
    --namespace {{ app_namespace }} \
    --repo {{ qotd_repo_url }} \
    --set host={{ instance_name }} \
    --set enableInstana=true \
    --set useNodePort=true \
    --set instanaReportingUrl={{ instanaReportingUrl }} \
    --set instanaEnumMinJsUrl={{ instanaEnumMinJsUrl }} \
    --set appNamespace={{ app_namespace }} \
    --set loadNamespace={{ app_namespace }}-load 
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml