- name: Install KubeCost with Helm
  ansible.builtin.shell: |
    helm upgrade --install kubecost \
    --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
    --namespace kubecost \
    --create-namespace \
    --set global.clusterId={{ instance_name }}
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Create Ingress
  ansible.builtin.shell: |
    kubectl apply -n kubecost -f - <<EOF
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: kubecost-ingress
      namespace: kubecost
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: kubecost
    spec:
      rules:
        - http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kubecost-cost-analyzer
                    port:
                      number: 9090
    EOF
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml