- name: Derive short hostname
  ansible.builtin.set_fact:
    short_hostname: "{{ new_hostname.split('.')[0] }}"

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"
  register: hostname_result

- name: Ensure 127.0.1.1 entry matches hostname (Ubuntu/Debian convention)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1 {{ new_hostname }} {{ short_hostname }}"
    create: true
    backup: true

- name: Prevent cloud-init from changing hostname on reboot
  when: guard_cloud_init
  block:
    - name: Preserve hostname in cloud-init
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/99-preserve-hostname.cfg
        owner: root
        group: root
        mode: '0644'
        content: |
          preserve_hostname: true

    - name: (Optional) record hostname for cloud-init clarity
      ansible.builtin.copy:
        dest: /etc/cloud/cloud.cfg.d/99-hostname.cfg
        owner: root
        group: root
        mode: '0644'
        content: |
          hostname: {{ short_hostname }}
          fqdn: {{ new_hostname }}

- name: Install dependencies
  ansible.builtin.package:
    name:
      - curl
      - sudo
      - jq
      - unzip
    state: present
    update_cache: true

- name: Download Helm installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run Helm installation script
  ansible.builtin.shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  register: helm_install_result
  changed_when: false

- name: Add /usr/local/bin to PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/usr/local/bin'
  when: helm_install_result.rc == 0