- name: Install k3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Start k3s service
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Ensure k3s config is readable
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: "0755"

- name: Install kubectl binary link
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Wait for Kubernetes API to become available
  become: false
  retries: 20
  delay: 5
  register: result
  until: result.rc == 0
  ansible.builtin.shell: kubectl get nodes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml