apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ ec2_public_ip.stdout }}/32
  - {{ ec2_ip }}/32 # Internal IP. If this is not NATted we might ahave issues so maybe double check for identity.
