ports:
  web:
    port: 80
    expose:
      default: true
    hostPort: 80
    protocol: TCP

  websecure:
    port: 443
    expose:
      default: true
    hostPort: 443
    protocol: TCP
    tls:
      enabled: true

  kubecost:
    port: 9090
    expose:
      default: true
    hostPort: 9090
    protocol: TCP
  
service:
  enabled: false  # ❗ verhindert, dass ein LoadBalancer-Service erzeugt wird